# Generated by Django 4.2.3 on 2023-10-16 20:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=30)),
                ('post_nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.IntegerField()),
                ('matricule', models.CharField(max_length=20)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_universite', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('contact', models.CharField(max_length=30)),
                ('website', models.TextField()),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.compte')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parcous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anne_acad', models.IntegerField()),
                ('cote', models.IntegerField()),
                ('mention', models.CharField(max_length=15)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Palmares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee', models.IntegerField()),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.universite')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField()),
                ('faculte', models.CharField(max_length=30)),
                ('promotion', models.CharField(max_length=30)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Etude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=30)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.etudiant')),
                ('palmares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.palmares')),
            ],
        ),
    ]
