# Generated by Django 4.2.6 on 2023-10-30 03:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=30)),
                ('post_nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateTimeField()),
                ('matricule', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=30)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='https://static.vecteezy.com/system/resources/thumbnails/005/545/335/small/user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector.jpg', upload_to='avatar_universites')),
                ('nom_universite', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('contact', models.CharField(max_length=30)),
                ('website', models.TextField()),
            ],
            options={
                'verbose_name': 'Université',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parcous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anne_acad', models.IntegerField(default=2000)),
                ('file', models.FileField(null=True, upload_to='parcours')),
                ('cote', models.IntegerField(default=0)),
                ('mention', models.CharField(default='Pas de mention', max_length=15)),
                ('promotion', models.CharField(default='L4 MSI', max_length=30)),
                ('universite', models.CharField(max_length=30)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Palmares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee', models.IntegerField()),
                ('file_first_sem', models.FileField(null=True, upload_to='palmares1')),
                ('file_second_sem', models.FileField(null=True, upload_to='palmares2')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.universite')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField()),
                ('faculte', models.CharField(max_length=30)),
                ('promotion', models.CharField(max_length=30)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Etude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=30)),
                ('valide', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.etudiant')),
                ('palmares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tranfertApp.palmares')),
            ],
        ),
    ]
