# Generated by Django 4.2.6 on 2023-10-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tranfertApp', '0002_alter_universite_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universite',
            name='compte',
        ),
    ]
