# Generated by Django 4.2.6 on 2023-10-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfertApp', '0003_remove_universite_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='compte',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='login',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='password',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
