# Generated by Django 4.2.6 on 2023-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfertApp', '0005_etude_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='login',
            field=models.CharField(max_length=30),
        ),
    ]
