# Generated by Django 4.2.6 on 2023-10-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfertApp', '0007_parcous_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universite',
            options={'verbose_name': 'Université'},
        ),
        migrations.AddField(
            model_name='parcous',
            name='file',
            field=models.FileField(null=True, upload_to='parcours'),
        ),
        migrations.AlterField(
            model_name='parcous',
            name='cote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parcous',
            name='mention',
            field=models.CharField(default='Pas de mention', max_length=15),
        ),
    ]
