# Generated by Django 4.2.6 on 2023-10-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfertApp', '0008_alter_universite_options_parcous_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palmares',
            name='file',
            field=models.FileField(null=True, upload_to='palmares'),
        ),
    ]
