# Generated by Django 4.2.6 on 2023-10-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfertApp', '0010_remove_palmares_file_palmares_file_first_sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateTimeField(),
        ),
    ]
