# Generated by Django 4.2.6 on 2023-10-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranfertApp', '0011_alter_etudiant_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='universite',
            name='avatar',
            field=models.ImageField(default='https://static.vecteezy.com/system/resources/thumbnails/005/545/335/small/user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector.jpg', upload_to='avatar_universites'),
        ),
    ]
